build-macos:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Mac App
      run: |
        pyinstaller --noconfirm --windowed \
          --hidden-import=torch \
          --hidden-import=tensorflow \
          --hidden-import=cv2 \
          --collect-all PyQt6 \
          --collect-all matplotlib \
          --collect-all moviepy \
          --add-data "emotion_detector_module.py:." \
          --add-data "algorithm_RR.py:." \
          --add-data "firebase_fetch.py:." \
          breathing_gui_ver7.py

    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: mac-app
        path: dist/*.app
