name: Build Mac App

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Firebase key
        run: |
          echo "${{ secrets.FIREBASE_SA_BASE64 }}" | base64 --decode > serviceAccountKey.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Mac app
        run: |
          pyinstaller --onefile --windowed \
          --name BioFeedbackApp \
          --add-data "algorithm_RR.py:." \
          --add-data "emotion_detector_module.py:." \
          --add-data "firebase_fetch.py:." \
          breathing_gui_ver7.py

      - name: Upload Mac build
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-App
          path: dist/*
